# Generated by Django 6.0.5 on 2026-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='joke',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
