# Generated by Django 6.0.5 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_jokes_joke'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='joke_hash',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
